import XCTest
import simd

@testable import TTCoach

/// Parity tests for `RTMPoseMath`. Expected values were generated by running the actual
/// rtmlib functions (and `cv2.getAffineTransform`) in the project venv against the same
/// inputs, then hard-coded here so the test target needs no Python at run time.
final class RTMPoseMathTests: XCTestCase {

    private let tol: Float = 1e-3

    // MARK: - letterbox

    func testLetterboxRatioAndSize() {
        // 1920x1080 -> ratio 1/3, size (640, 360)
        XCTAssertEqual(RTMPoseMath.letterboxRatio(imageWidth: 1920, imageHeight: 1080), 1.0 / 3.0, accuracy: 1e-6)
        var sz = RTMPoseMath.letterboxResizedSize(imageWidth: 1920, imageHeight: 1080)
        XCTAssertEqual(sz.w, 640); XCTAssertEqual(sz.h, 360)

        // 640x480 -> ratio 1, size (640, 480)
        XCTAssertEqual(RTMPoseMath.letterboxRatio(imageWidth: 640, imageHeight: 480), 1.0, accuracy: 1e-6)
        sz = RTMPoseMath.letterboxResizedSize(imageWidth: 640, imageHeight: 480)
        XCTAssertEqual(sz.w, 640); XCTAssertEqual(sz.h, 480)

        // 720x1280 -> ratio 0.5, size (360, 640)
        XCTAssertEqual(RTMPoseMath.letterboxRatio(imageWidth: 720, imageHeight: 1280), 0.5, accuracy: 1e-6)
        sz = RTMPoseMath.letterboxResizedSize(imageWidth: 720, imageHeight: 1280)
        XCTAssertEqual(sz.w, 360); XCTAssertEqual(sz.h, 640)
    }

    // MARK: - bbox_xyxy2cs (padding 1.25)

    func testBboxXyxyToCenterScale() {
        // [100,50,300,450] -> center (200,250), scale (250,500)
        var r = RTMPoseMath.bboxXyxyToCenterScale(x1: 100, y1: 50, x2: 300, y2: 450)
        assertSIMD2(r.center, 200, 250)
        assertSIMD2(r.scale, 250, 500)

        // [0,0,640,480] -> center (320,240), scale (800,600)
        r = RTMPoseMath.bboxXyxyToCenterScale(x1: 0, y1: 0, x2: 640, y2: 480)
        assertSIMD2(r.center, 320, 240)
        assertSIMD2(r.scale, 800, 600)
    }

    // MARK: - top_down_affine aspect fix (aspect = 192/256 = 0.75)

    func testTopDownAffineScaleFix() {
        // w > h*aspect branch: [400,200] -> [400, 533.3333]
        var s = RTMPoseMath.topDownAffineScale(scale: SIMD2<Float>(400, 200), outputW: 192, outputH: 256)
        assertSIMD2(s, 400, 533.3333)

        // w < h*aspect branch: [100,400] -> [300, 400]
        s = RTMPoseMath.topDownAffineScale(scale: SIMD2<Float>(100, 400), outputW: 192, outputH: 256)
        assertSIMD2(s, 300, 400)
    }

    // MARK: - cv2.getAffineTransform

    func testAffineFromPointPairs() {
        let src = [SIMD2<Float>(0, 0), SIMD2<Float>(1, 0), SIMD2<Float>(0, 1)]
        let dst = [SIMD2<Float>(10, 20), SIMD2<Float>(14, 22), SIMD2<Float>(8, 26)]
        let m = RTMPoseMath.affineFromPointPairs(src: src, dst: dst)
        // Oracle flatten: [4, -2, 10, 2, 6, 20]
        assertFlat(RTMPoseMath.affine2x3Flat(m), [4, -2, 10, 2, 6, 20])

        // Round-trip: M applied to each src must yield dst.
        for i in 0..<3 {
            assertSIMD2(RTMPoseMath.affine2x3Apply(m, src[i]), dst[i].x, dst[i].y)
        }
    }

    // MARK: - get_warp_matrix (rot = 0)

    func testGetWarpMatrix() {
        // center (200,250) scale (300,400) out (192,256) -> [0.64, 0, -32, 0, 0.64, -32]
        var m = RTMPoseMath.getWarpMatrix(
            center: SIMD2<Float>(200, 250), scale: SIMD2<Float>(300, 400),
            rotDeg: 0, outputW: 192, outputH: 256, inverse: false)
        assertFlat(RTMPoseMath.affine2x3Flat(m), [0.64, 0.0, -32.0, 0.0, 0.64, -32.0])

        // center (320,240) scale (250,500) out (192,256) -> [0.768, 0, -149.76, 0, 0.768, -56.32]
        m = RTMPoseMath.getWarpMatrix(
            center: SIMD2<Float>(320, 240), scale: SIMD2<Float>(250, 500),
            rotDeg: 0, outputW: 192, outputH: 256, inverse: false)
        assertFlat(RTMPoseMath.affine2x3Flat(m), [0.768, 0.0, -149.76, 0.0, 0.768, -56.32])
    }

    func testGetWarpMatrixRotated() {
        // Exercises the rotDeg != 0 path (rotatePoint sin/cos). Oracle from rtmlib
        // get_warp_matrix(center=(400,300), scale=(360,480), rot=30, out=(192,256)).
        let m = RTMPoseMath.getWarpMatrix(
            center: SIMD2<Float>(400, 300), scale: SIMD2<Float>(360, 480),
            rotDeg: 30, outputW: 192, outputH: 256, inverse: false)
        assertFlat(RTMPoseMath.affine2x3Flat(m),
                   [0.46188, 0.26667, -168.75207, -0.26667, 0.46188, 96.10259])
    }

    func testGetWarpMatrixInverseRoundTrips() {
        // inverse=True should map dst-space back to src-space: forward(inverse(p)) == p.
        let center = SIMD2<Float>(200, 250)
        let scale = SIMD2<Float>(300, 400)
        let fwd = RTMPoseMath.getWarpMatrix(center: center, scale: scale, rotDeg: 0,
                                            outputW: 192, outputH: 256, inverse: false)
        let inv = RTMPoseMath.getWarpMatrix(center: center, scale: scale, rotDeg: 0,
                                            outputW: 192, outputH: 256, inverse: true)
        let p = SIMD2<Float>(100, 130)
        let back = RTMPoseMath.affine2x3Apply(fwd, RTMPoseMath.affine2x3Apply(inv, p))
        assertSIMD2(back, p.x, p.y)
    }

    // MARK: - get_simcc_maximum

    func testSimccMaximumSmall() {
        // K=2. kp0: argmax_x=1, argmax_y=2, val=0.5*(0.9+0.5)=0.7
        // kp1: all-zero x, all-negative y -> val<=0 -> loc (-1,-1)
        let sx: [[Float]] = [[0.1, 0.9, 0.2, 0.0], [0.0, 0.0, 0.0, 0.0]]
        let sy: [[Float]] = [[0.0, 0.0, 0.5, 0.3, 0.1], [-0.1, -0.2, -0.3, -0.4, -0.5]]
        let r = RTMPoseMath.simccMaximum(simccX: sx, simccY: sy)
        assertSIMD2(r.locs[0], 1, 2)
        XCTAssertEqual(r.vals[0], 0.7, accuracy: tol)
        assertSIMD2(r.locs[1], -1, -1)
        XCTAssertEqual(r.vals[1], -0.05, accuracy: tol)
    }

    func testSimccMaximumK17OneHot() {
        let K = 17, Wx = 384, Wy = 512
        var sx = [[Float]](repeating: [Float](repeating: 0, count: Wx), count: K)
        var sy = [[Float]](repeating: [Float](repeating: 0, count: Wy), count: K)
        for k in 0..<K {
            sx[k][(k * 7) % Wx] = 0.8 + 0.01 * Float(k)
            sy[k][(k * 11) % Wy] = 0.6 + 0.01 * Float(k)
        }
        let r = RTMPoseMath.simccMaximum(simccX: sx, simccY: sy)
        for k in 0..<K {
            // Oracle argmaxes: x=(k*7)%Wx, y=(k*11)%Wy; val=0.5*((0.8+0.01k)+(0.6+0.01k))=0.7+0.01k
            assertSIMD2(r.locs[k], Float((k * 7) % Wx), Float((k * 11) % Wy))
            XCTAssertEqual(r.vals[k], 0.7 + 0.01 * Float(k), accuracy: tol)
        }
    }

    func testSimccMaximumTieTakesFirstIndex() {
        // numpy argmax returns the FIRST maximal index. Locks in the strict-`>`
        // semantics (a `>=` regression would pick the last index instead).
        let sx: [[Float]] = [[0.2, 0.8, 0.8, 0.3]]   // tie at idx 1 and 2 -> expect 1
        let sy: [[Float]] = [[0.9, 0.9, 0.1]]        // tie at idx 0 and 1 -> expect 0
        let r = RTMPoseMath.simccMaximum(simccX: sx, simccY: sy)
        assertSIMD2(r.locs[0], 1, 0)
    }

    func testSimccMaximumAllZeroIsExcluded() {
        let sx: [[Float]] = [[0.0, 0.0, 0.0]]
        let sy: [[Float]] = [[0.0, 0.0, 0.0]]
        let r = RTMPoseMath.simccMaximum(simccX: sx, simccY: sy)
        assertSIMD2(r.locs[0], -1, -1) // val == 0 -> excluded
        XCTAssertEqual(r.vals[0], 0.0, accuracy: tol)
    }

    // MARK: - decodeKeypoints chain

    func testDecodeKeypoints() {
        let locs = [SIMD2<Float>(100, 200), SIMD2<Float>(50, 75), SIMD2<Float>(383, 511)]
        let center = SIMD2<Float>(320, 240)
        let scale = SIMD2<Float>(300, 400)
        let out = RTMPoseMath.decodeKeypoints(locs: locs, center: center, scale: scale)
        // Oracle: [[248.125, 196.25], [209.0625, 98.59375], [469.21875, 439.21875]]
        assertSIMD2(out[0], 248.125, 196.25)
        assertSIMD2(out[1], 209.0625, 98.59375)
        assertSIMD2(out[2], 469.21875, 439.21875)
    }

    // MARK: - constants sanity

    func testConstants() {
        XCTAssertEqual(RTMPoseMath.meanBGR, [123.675, 116.28, 103.53])
        XCTAssertEqual(RTMPoseMath.stdBGR, [58.395, 57.12, 57.375])
        XCTAssertEqual(RTMPoseMath.simccSplitRatio, 2.0)
        XCTAssertEqual(RTMPoseMath.detScoreThreshold, 0.3, accuracy: 1e-6)
        XCTAssertEqual(RTMPoseMath.poseInputW, 192)
        XCTAssertEqual(RTMPoseMath.poseInputH, 256)
        XCTAssertEqual(RTMPoseMath.detInput, 640)
        XCTAssertEqual(RTMPoseMath.poseAspectRatio, 0.75, accuracy: 1e-6)
    }

    // MARK: - helpers

    private func assertSIMD2(_ v: SIMD2<Float>, _ x: Float, _ y: Float,
                             file: StaticString = #filePath, line: UInt = #line) {
        XCTAssertEqual(v.x, x, accuracy: tol, file: file, line: line)
        XCTAssertEqual(v.y, y, accuracy: tol, file: file, line: line)
    }

    private func assertFlat(_ got: [Float], _ expected: [Float],
                            file: StaticString = #filePath, line: UInt = #line) {
        XCTAssertEqual(got.count, expected.count, file: file, line: line)
        for i in 0..<min(got.count, expected.count) {
            XCTAssertEqual(got[i], expected[i], accuracy: tol, file: file, line: line)
        }
    }
}
