package com.ttcoachai.pose

import org.junit.Assert.assertEquals
import org.junit.Test

/**
 * Parity tests for [RtmposeMath]. Ported 1:1 from the iOS
 * `iosApp/TTCoach/Pose/RTMPoseMathTests.swift`. Expected values were generated by running the
 * actual rtmlib functions (and `cv2.getAffineTransform`) in the project venv against the same
 * inputs, then hard-coded here (and in the Swift original) so tests need no Python at run time.
 */
class RtmposeMathTest {

    private val tol = 1e-3f

    // MARK: - letterbox

    @Test
    fun testLetterboxRatioAndSize() {
        // 1920x1080 -> ratio 1/3, size (640, 360)
        assertEquals(1.0f / 3.0f, RtmposeMath.letterboxRatio(1920, 1080), 1e-6f)
        var sz = RtmposeMath.letterboxResizedSize(1920, 1080)
        assertEquals(640, sz.first)
        assertEquals(360, sz.second)

        // 640x480 -> ratio 1, size (640, 480)
        assertEquals(1.0f, RtmposeMath.letterboxRatio(640, 480), 1e-6f)
        sz = RtmposeMath.letterboxResizedSize(640, 480)
        assertEquals(640, sz.first)
        assertEquals(480, sz.second)

        // 720x1280 -> ratio 0.5, size (360, 640)
        assertEquals(0.5f, RtmposeMath.letterboxRatio(720, 1280), 1e-6f)
        sz = RtmposeMath.letterboxResizedSize(720, 1280)
        assertEquals(360, sz.first)
        assertEquals(640, sz.second)
    }

    // MARK: - bbox_xyxy2cs (padding 1.25)

    @Test
    fun testBboxXyxyToCenterScale() {
        // [100,50,300,450] -> center (200,250), scale (250,500)
        var r = RtmposeMath.bboxXyxyToCenterScale(100f, 50f, 300f, 450f)
        assertVec2(r.center, 200f, 250f)
        assertVec2(r.scale, 250f, 500f)

        // [0,0,640,480] -> center (320,240), scale (800,600)
        r = RtmposeMath.bboxXyxyToCenterScale(0f, 0f, 640f, 480f)
        assertVec2(r.center, 320f, 240f)
        assertVec2(r.scale, 800f, 600f)
    }

    // MARK: - top_down_affine aspect fix (aspect = 192/256 = 0.75)

    @Test
    fun testTopDownAffineScaleFix() {
        // w > h*aspect branch: [400,200] -> [400, 533.3333]
        var s = RtmposeMath.topDownAffineScale(Vec2(400f, 200f), outputW = 192, outputH = 256)
        assertVec2(s, 400f, 533.3333f)

        // w < h*aspect branch: [100,400] -> [300, 400]
        s = RtmposeMath.topDownAffineScale(Vec2(100f, 400f), outputW = 192, outputH = 256)
        assertVec2(s, 300f, 400f)
    }

    // MARK: - cv2.getAffineTransform

    @Test
    fun testAffineFromPointPairs() {
        val src = listOf(Vec2(0f, 0f), Vec2(1f, 0f), Vec2(0f, 1f))
        val dst = listOf(Vec2(10f, 20f), Vec2(14f, 22f), Vec2(8f, 26f))
        val m = RtmposeMath.affineFromPointPairs(src, dst)
        // Oracle flatten: [4, -2, 10, 2, 6, 20]
        assertFlat(RtmposeMath.affine2x3Flat(m), floatArrayOf(4f, -2f, 10f, 2f, 6f, 20f))

        // Round-trip: M applied to each src must yield dst.
        for (i in 0..2) {
            assertVec2(RtmposeMath.affine2x3Apply(m, src[i]), dst[i].x, dst[i].y)
        }
    }

    // MARK: - get_warp_matrix (rot = 0)

    @Test
    fun testGetWarpMatrix() {
        // center (200,250) scale (300,400) out (192,256) -> [0.64, 0, -32, 0, 0.64, -32]
        var m = RtmposeMath.getWarpMatrix(
            center = Vec2(200f, 250f), scale = Vec2(300f, 400f),
            rotDeg = 0f, outputW = 192, outputH = 256, inverse = false
        )
        assertFlat(RtmposeMath.affine2x3Flat(m), floatArrayOf(0.64f, 0.0f, -32.0f, 0.0f, 0.64f, -32.0f))

        // center (320,240) scale (250,500) out (192,256) -> [0.768, 0, -149.76, 0, 0.768, -56.32]
        m = RtmposeMath.getWarpMatrix(
            center = Vec2(320f, 240f), scale = Vec2(250f, 500f),
            rotDeg = 0f, outputW = 192, outputH = 256, inverse = false
        )
        assertFlat(RtmposeMath.affine2x3Flat(m), floatArrayOf(0.768f, 0.0f, -149.76f, 0.0f, 0.768f, -56.32f))
    }

    @Test
    fun testGetWarpMatrixRotated() {
        // Exercises the rotDeg != 0 path (rotatePoint sin/cos). Oracle from rtmlib
        // get_warp_matrix(center=(400,300), scale=(360,480), rot=30, out=(192,256)).
        val m = RtmposeMath.getWarpMatrix(
            center = Vec2(400f, 300f), scale = Vec2(360f, 480f),
            rotDeg = 30f, outputW = 192, outputH = 256, inverse = false
        )
        assertFlat(
            RtmposeMath.affine2x3Flat(m),
            floatArrayOf(0.46188f, 0.26667f, -168.75207f, -0.26667f, 0.46188f, 96.10259f)
        )
    }

    @Test
    fun testGetWarpMatrixInverseRoundTrips() {
        // inverse=True should map dst-space back to src-space: forward(inverse(p)) == p.
        val center = Vec2(200f, 250f)
        val scale = Vec2(300f, 400f)
        val fwd = RtmposeMath.getWarpMatrix(
            center = center, scale = scale, rotDeg = 0f,
            outputW = 192, outputH = 256, inverse = false
        )
        val inv = RtmposeMath.getWarpMatrix(
            center = center, scale = scale, rotDeg = 0f,
            outputW = 192, outputH = 256, inverse = true
        )
        val p = Vec2(100f, 130f)
        val back = RtmposeMath.affine2x3Apply(fwd, RtmposeMath.affine2x3Apply(inv, p))
        assertVec2(back, p.x, p.y)
    }

    // MARK: - get_simcc_maximum

    @Test
    fun testSimccMaximumSmall() {
        // K=2. kp0: argmax_x=1, argmax_y=2, val=0.5*(0.9+0.5)=0.7
        // kp1: all-zero x, all-negative y -> val<=0 -> loc (-1,-1)
        val sx = arrayOf(
            floatArrayOf(0.1f, 0.9f, 0.2f, 0.0f),
            floatArrayOf(0.0f, 0.0f, 0.0f, 0.0f)
        )
        val sy = arrayOf(
            floatArrayOf(0.0f, 0.0f, 0.5f, 0.3f, 0.1f),
            floatArrayOf(-0.1f, -0.2f, -0.3f, -0.4f, -0.5f)
        )
        val r = RtmposeMath.simccMaximum(sx, sy)
        assertVec2(r.locs[0], 1f, 2f)
        assertEquals(0.7f, r.vals[0], tol)
        assertVec2(r.locs[1], -1f, -1f)
        assertEquals(-0.05f, r.vals[1], tol)
    }

    @Test
    fun testSimccMaximumK17OneHot() {
        val k = 17
        val wx = 384
        val wy = 512
        val sx = Array(k) { FloatArray(wx) }
        val sy = Array(k) { FloatArray(wy) }
        for (ki in 0 until k) {
            sx[ki][(ki * 7) % wx] = 0.8f + 0.01f * ki
            sy[ki][(ki * 11) % wy] = 0.6f + 0.01f * ki
        }
        val r = RtmposeMath.simccMaximum(sx, sy)
        for (ki in 0 until k) {
            // Oracle argmaxes: x=(k*7)%Wx, y=(k*11)%Wy; val=0.5*((0.8+0.01k)+(0.6+0.01k))=0.7+0.01k
            assertVec2(r.locs[ki], ((ki * 7) % wx).toFloat(), ((ki * 11) % wy).toFloat())
            assertEquals(0.7f + 0.01f * ki, r.vals[ki], tol)
        }
    }

    @Test
    fun testSimccMaximumTieTakesFirstIndex() {
        // numpy argmax returns the FIRST maximal index. Locks in the strict-`>`
        // semantics (a `>=` regression would pick the last index instead).
        val sx = arrayOf(floatArrayOf(0.2f, 0.8f, 0.8f, 0.3f)) // tie at idx 1 and 2 -> expect 1
        val sy = arrayOf(floatArrayOf(0.9f, 0.9f, 0.1f)) // tie at idx 0 and 1 -> expect 0
        val r = RtmposeMath.simccMaximum(sx, sy)
        assertVec2(r.locs[0], 1f, 0f)
    }

    @Test
    fun testSimccMaximumAllZeroIsExcluded() {
        val sx = arrayOf(floatArrayOf(0.0f, 0.0f, 0.0f))
        val sy = arrayOf(floatArrayOf(0.0f, 0.0f, 0.0f))
        val r = RtmposeMath.simccMaximum(sx, sy)
        assertVec2(r.locs[0], -1f, -1f) // val == 0 -> excluded
        assertEquals(0.0f, r.vals[0], tol)
    }

    // MARK: - decodeKeypoints chain

    @Test
    fun testDecodeKeypoints() {
        val locs = listOf(Vec2(100f, 200f), Vec2(50f, 75f), Vec2(383f, 511f))
        val center = Vec2(320f, 240f)
        val scale = Vec2(300f, 400f)
        val out = RtmposeMath.decodeKeypoints(locs, center, scale)
        // Oracle: [[248.125, 196.25], [209.0625, 98.59375], [469.21875, 439.21875]]
        assertVec2(out[0], 248.125f, 196.25f)
        assertVec2(out[1], 209.0625f, 98.59375f)
        assertVec2(out[2], 469.21875f, 439.21875f)
    }

    // MARK: - constants sanity

    @Test
    fun testConstants() {
        assertEquals(listOf(123.675f, 116.28f, 103.53f), RtmposeMath.meanBGR)
        assertEquals(listOf(58.395f, 57.12f, 57.375f), RtmposeMath.stdBGR)
        assertEquals(2.0f, RtmposeMath.simccSplitRatio, 0f)
        assertEquals(0.3f, RtmposeMath.detScoreThreshold, 1e-6f)
        assertEquals(192, RtmposeMath.poseInputW)
        assertEquals(256, RtmposeMath.poseInputH)
        assertEquals(640, RtmposeMath.detInput)
        assertEquals(0.75f, RtmposeMath.poseAspectRatio, 1e-6f)
    }

    // MARK: - helpers

    private fun assertVec2(v: Vec2, x: Float, y: Float) {
        assertEquals(x, v.x, tol)
        assertEquals(y, v.y, tol)
    }

    private fun assertFlat(got: FloatArray, expected: FloatArray) {
        assertEquals(expected.size, got.size)
        for (i in expected.indices) {
            assertEquals(expected[i], got[i], tol)
        }
    }
}
